// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_web_exam_api.Context;

#nullable disable

namespace csharp_web_exam_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240305193837_AgregarBaseDatosAlumno")]
    partial class AgregarBaseDatosAlumno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("csharp_web_exam_api.Models.ALUMNO", b =>
                {
                    b.Property<int>("ALUMNO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ALUMNO_ID"));

                    b.Property<string>("CORREO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GENERO_ID")
                        .HasColumnType("int");

                    b.Property<string>("MATERNO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PATERNO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ALUMNO_ID");

                    b.HasIndex("ALUMNO_ID")
                        .IsUnique();

                    b.HasIndex("GENERO_ID");

                    b.ToTable("ALUMNO", "test");
                });

            modelBuilder.Entity("csharp_web_exam_api.Models.GENERO", b =>
                {
                    b.Property<int>("GENERO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GENERO_ID"));

                    b.Property<string>("GENERO_DESC")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("GENERO_ID");

                    b.HasIndex("GENERO_ID")
                        .IsUnique();

                    b.ToTable("GENERO", "test");
                });

            modelBuilder.Entity("csharp_web_exam_api.Models.ALUMNO", b =>
                {
                    b.HasOne("csharp_web_exam_api.Models.GENERO", "GENERO")
                        .WithMany()
                        .HasForeignKey("GENERO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GENERO");
                });
#pragma warning restore 612, 618
        }
    }
}
